New Workflow

diff --git a/.github/workflows/Server-BasicSetup.yml b/.github/workflows/Server-BasicSetup.yml
--- a/.github/workflows/Server-BasicSetup.yml
+++ b/.github/workflows/Server-BasicSetup.yml
@@ -69,27 +69,28 @@ jobs:
 
     # Create Secret for Ingress SSL
     - name: Create Secret Ingress SSL
-      env:
-        SSL_CERT: ${{ secrets.SSL_INGRESS_SIMPLYSTU_CERT }}
-        SSL_KEY: ${{ secrets.SSL_INGRESS_SIMPLYSTU_KEY }}
-      run: |
-        sshpass -p "${{ secrets.SSH_ALEX_SERVER_PW }}" ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SSH_ALEX_SERVER_IP }} bash << 'EOF'
-          # Create temporary files for the certificate and key
-          echo "$SSL_CERT" > /tmp/cert.crt
-          echo "$SSL_KEY" > /tmp/cert.key
-    
-          # Check that the files were created successfully
-          if [ ! -s /tmp/cert.crt ] || [ ! -s /tmp/cert.key ]; then
-            echo "Failed to create certificate or key file."
-            exit 1
-          fi
-    
-          # Create the Kubernetes secret using the files
-          kubectl create secret tls petclinic-tls --cert=/tmp/cert.crt --key=/tmp/cert.key --namespace=dev
-    
-          # Clean up the temporary files
-          rm /tmp/cert.crt /tmp/cert.key
-        EOF
+    env:
+      SSL_CERT: ${{ secrets.SSL_INGRESS_SIMPLYSTU_CERT }}
+      SSL_KEY: ${{ secrets.SSL_INGRESS_SIMPLYSTU_KEY }}
+    run: |
+      sshpass -p "${{ secrets.SSH_ALEX_SERVER_PW }}" ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SSH_ALEX_SERVER_IP }} bash << 'EOF'
+        # Decode the base64 encoded secrets and write to temporary files
+        echo "$SSL_CERT" > /tmp/cert.crt
+        echo "$SSL_KEY" > /tmp/cert.key
+  
+        # Check that the files contain PEM data
+        if ! grep -q "-----BEGIN" /tmp/cert.crt || ! grep -q "-----BEGIN" /tmp/cert.key; then
+          echo "The certificate or key does not contain valid PEM data."
+          exit 1
+        fi
+  
+        # Create the Kubernetes secret using the files
+        kubectl create secret tls petclinic-tls --cert=/tmp/cert.crt --key=/tmp/cert.key --namespace=dev
+  
+        # Clean up the temporary files
+        rm /tmp/cert.crt /tmp/cert.key
+      EOF
+  
   
 
 
